#!/bin/bash
current_dir="$PWD";parent_dir="$(dirname "$current_dir")";for file in $(find "$current_dir" -name '*.html' -type f);do filename=$(basename "$file");if [ ! -e "$parent_dir/$filename" ] || [ "$file" -nt "$parent_dir/$filename" ];then cp "$file" "$parent_dir";echo "Copied $filename to $parent_dir";fi;done
